# ============================================================
# utils/report_generator.py
# PDF & Text Report Generator
# ============================================================

import io
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_text_report(analysis: dict, resume_filename: str = "resume") -> str:
    """
    Generate a plain-text analysis report.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    score = analysis.get("ats_score", 0)

    lines = [
        "=" * 65,
        "  🚀 AI RESUME ANALYZER — ATS ANALYSIS REPORT",
        "=" * 65,
        f"  Generated: {now}",
        f"  Resume:    {resume_filename}",
        "=" * 65,
        "",
        f"  ⭐ ATS SCORE: {score:.1f} / 100",
        f"  🔒 Confidence: {analysis.get('confidence_score', 0):.1f}%",
        "",
        "─" * 65,
        "  📊 SCORE BREAKDOWN",
        "─" * 65,
        f"  Semantic Similarity:  {analysis.get('semantic_similarity', 0):.1f}%",
        f"  Skill Match:          {analysis.get('skill_match_pct', 0):.1f}%",
        f"  Keyword Match:        {analysis.get('keyword_match_pct', 0):.1f}%",
        f"  Experience Score:     {analysis.get('experience_score', 0):.1f}%",
        f"  Education Score:      {analysis.get('education_score', 0):.1f}%",
        f"  Format Quality:       {analysis.get('format_score', 0):.1f}%",
        "",
        "─" * 65,
        "  ✅ MATCHED SKILLS",
        "─" * 65,
    ]

    matched = analysis.get("matched_skills", [])
    if matched:
        for i in range(0, len(matched), 5):
            lines.append("  " + " | ".join(matched[i:i+5]))
    else:
        lines.append("  No matched skills found.")

    lines += [
        "",
        "─" * 65,
        "  ❌ MISSING SKILLS (Add these!)",
        "─" * 65,
    ]

    missing = analysis.get("missing_skills", [])
    if missing:
        for i in range(0, len(missing), 5):
            lines.append("  " + " | ".join(missing[i:i+5]))
    else:
        lines.append("  No critical missing skills.")

    lines += [
        "",
        "─" * 65,
        "  🔑 MISSING KEYWORDS",
        "─" * 65,
    ]
    missing_kw = analysis.get("missing_keywords", [])
    if missing_kw:
        lines.append("  " + " | ".join(list(missing_kw)[:15]))
    else:
        lines.append("  Good keyword coverage!")

    lines += [
        "",
        "─" * 65,
        "  💡 IMPROVEMENT SUGGESTIONS",
        "─" * 65,
    ]
    for i, sug in enumerate(analysis.get("improvement_suggestions", []), 1):
        lines.append(f"  {i}. [{sug.get('priority', '')}] {sug.get('category', '')}")
        lines.append(f"     → {sug.get('suggestion', '')}")
        lines.append(f"     Impact: {sug.get('impact', '')}")
        lines.append("")

    lines += [
        "─" * 65,
        "  ✍️  RESUME REWRITE EXAMPLES (Before → After)",
        "─" * 65,
    ]
    for rw in analysis.get("rewrite_bullets", [])[:5]:
        lines.append(f"  BEFORE: {rw.get('before', '')}")
        lines.append(f"  AFTER:  {rw.get('after', '')}")
        lines.append(f"  TIP:    {rw.get('tip', '')}")
        lines.append("")

    lines += [
        "=" * 65,
        "  Generated by 🚀 Offline RAG Resume Analyzer",
        "  github.com/your-username/resume-analyzer",
        "=" * 65,
    ]

    return "\n".join(lines)


def generate_pdf_report(analysis: dict, resume_filename: str = "resume") -> bytes:
    """
    Generate a styled PDF analysis report using reportlab.
    Returns PDF bytes.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer,
            Table, TableStyle, HRFlowable
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        logger.warning("reportlab not found, generating text report instead.")
        text = generate_text_report(analysis, resume_filename)
        return text.encode("utf-8")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    # Styles
    styles = getSampleStyleSheet()
    DARK = colors.HexColor("#0f0f1a")
    ACCENT = colors.HexColor("#7c3aed")
    SUCCESS = colors.HexColor("#22c55e")
    WARNING = colors.HexColor("#f59e0b")
    DANGER = colors.HexColor("#ef4444")
    MUTED = colors.HexColor("#6b7280")
    WHITE = colors.white

    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontName="Helvetica-Bold", fontSize=22,
        textColor=ACCENT, alignment=TA_CENTER, spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontName="Helvetica", fontSize=10,
        textColor=MUTED, alignment=TA_CENTER, spaceAfter=16,
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Heading2"],
        fontName="Helvetica-Bold", fontSize=13,
        textColor=ACCENT, spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9,
        textColor=DARK, spaceAfter=4,
    )
    code_style = ParagraphStyle(
        "Code", parent=styles["Normal"],
        fontName="Courier", fontSize=8,
        textColor=DARK, spaceAfter=3, leftIndent=12,
    )

    story = []
    now = datetime.now().strftime("%B %d, %Y %H:%M")
    score = analysis.get("ats_score", 0)

    # Header
    story.append(Paragraph("🚀 AI Resume Analyzer", title_style))
    story.append(Paragraph(f"ATS Analysis Report — {now}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
    story.append(Spacer(1, 12))

    # Score Card Table
    score_color = SUCCESS if score >= 75 else (WARNING if score >= 50 else DANGER)
    score_data = [
        ["ATS Score", "Confidence", "Skill Match", "Keyword Match"],
        [
            f"{score:.1f}%",
            f"{analysis.get('confidence_score', 0):.1f}%",
            f"{analysis.get('skill_match_pct', 0):.1f}%",
            f"{analysis.get('keyword_match_pct', 0):.1f}%",
        ]
    ]
    score_table = Table(score_data, colWidths=[4 * cm, 4 * cm, 4 * cm, 4 * cm])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, 1), 14),
        ("TEXTCOLOR", (0, 1), (0, 1), score_color),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f3f4f6")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [ACCENT, colors.HexColor("#f9fafb")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 16))

    # Score Breakdown
    story.append(Paragraph("📊 Detailed Score Breakdown", h2_style))
    breakdown_data = [
        ["Component", "Score", "Weight"],
        ["Semantic Similarity", f"{analysis.get('semantic_similarity', 0):.1f}%", "30%"],
        ["Skill Match", f"{analysis.get('skill_match_pct', 0):.1f}%", "25%"],
        ["Keyword Match", f"{analysis.get('keyword_match_pct', 0):.1f}%", "25%"],
        ["Experience Alignment", f"{analysis.get('experience_score', 0):.1f}%", "10%"],
        ["Education Match", f"{analysis.get('education_score', 0):.1f}%", "5%"],
        ["Format Quality", f"{analysis.get('format_score', 0):.1f}%", "5%"],
    ]
    bkd_table = Table(breakdown_data, colWidths=[8 * cm, 4 * cm, 4 * cm])
    bkd_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, colors.HexColor("#f9fafb")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(bkd_table)
    story.append(Spacer(1, 12))

    # Matched Skills
    matched = analysis.get("matched_skills", [])
    story.append(Paragraph(f"✅ Matched Skills ({len(matched)})", h2_style))
    if matched:
        story.append(Paragraph(", ".join(matched), body_style))
    else:
        story.append(Paragraph("No matched skills detected.", body_style))

    # Missing Skills
    missing = analysis.get("missing_skills", [])
    story.append(Paragraph(f"❌ Missing Skills ({len(missing)})", h2_style))
    if missing:
        story.append(Paragraph(", ".join(missing), body_style))
    else:
        story.append(Paragraph("No critical missing skills.", body_style))

    # Improvement Suggestions
    story.append(Paragraph("💡 Improvement Suggestions", h2_style))
    for i, sug in enumerate(analysis.get("improvement_suggestions", [])[:8], 1):
        priority = sug.get("priority", "")
        p_color = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(priority, "⚪")
        story.append(Paragraph(
            f"<b>{p_color} {i}. {sug.get('category', '')}</b>",
            body_style,
        ))
        story.append(Paragraph(f"→ {sug.get('suggestion', '')}", code_style))
        story.append(Paragraph(
            f"<i>Impact: {sug.get('impact', '')}</i>",
            ParagraphStyle("Italic", parent=body_style, textColor=MUTED, fontSize=8),
        ))
        story.append(Spacer(1, 4))

    # Rewrite Examples
    story.append(Paragraph("✍️ Resume Rewrite Examples", h2_style))
    for rw in analysis.get("rewrite_bullets", [])[:5]:
        story.append(Paragraph(f"<b>Before:</b> {rw.get('before', '')}", code_style))
        story.append(Paragraph(
            f"<b>After:</b> {rw.get('after', '')}",
            ParagraphStyle("After", parent=code_style, textColor=SUCCESS),
        ))
        story.append(Paragraph(
            f"<i>💡 {rw.get('tip', '')}</i>",
            ParagraphStyle("Tip", parent=body_style, textColor=MUTED, fontSize=8, leftIndent=12),
        ))
        story.append(Spacer(1, 8))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=MUTED))
    story.append(Paragraph(
        "Generated by 🚀 Offline RAG Resume Analyzer | Fully local, no paid APIs",
        ParagraphStyle("Footer", parent=body_style, textColor=MUTED, alignment=TA_CENTER, fontSize=8),
    ))

    doc.build(story)
    return buffer.getvalue()
