# ============================================================
# services/export_service.py
# Export Service — generate optimized resumes as PDF/DOCX
# ============================================================

import io
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_optimized_pdf(optimization_result: dict, resume_name: str = "resume") -> bytes:
    """
    Generate a professionally formatted PDF of the optimized resume.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable, ListFlowable, ListItem
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        return _fallback_text_export(optimization_result).encode("utf-8")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    ACCENT = colors.HexColor("#7c3aed")
    DARK = colors.HexColor("#1e1e2e")
    MUTED = colors.HexColor("#6b7280")
    SUCCESS = colors.HexColor("#22c55e")

    name_style = ParagraphStyle("Name", parent=styles["Title"],
        fontName="Helvetica-Bold", fontSize=22, textColor=DARK,
        alignment=TA_CENTER, spaceAfter=4)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"],
        fontName="Helvetica-Bold", fontSize=12, textColor=ACCENT,
        spaceBefore=14, spaceAfter=4)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
        fontName="Helvetica", fontSize=10, textColor=DARK,
        spaceAfter=4, leading=14)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9.5, textColor=DARK,
        spaceAfter=3, leading=13, leftIndent=12, bulletIndent=0)
    note_style = ParagraphStyle("Note", parent=styles["Normal"],
        fontName="Helvetica-Oblique", fontSize=8, textColor=SUCCESS,
        spaceAfter=6, alignment=TA_CENTER)

    sections = optimization_result.get("optimized_sections", {})
    est_score = optimization_result.get("estimated_new_ats_score", 0)
    improvement = optimization_result.get("improvement_percentage", 0)

    story = []

    # Extract actual name from header section (first non-empty line)
    header_text = sections.get("header", "")
    header_lines = [l.strip() for l in header_text.split("\n") if l.strip()]
    if header_lines:
        display_name = header_lines[0]
        contact_lines = header_lines[1:]
    else:
        display_name = resume_name.replace("_", " ").replace("-", " ").title()
        display_name = display_name.replace(".Pdf", "").replace(".Docx", "").replace(".Doc", "")
        contact_lines = []

    story.append(Paragraph(display_name, name_style))
    story.append(Paragraph(
        f"ATS-Optimized Resume · Estimated Score: ~{est_score:.0f}% (↑{improvement:.0f}% improvement)",
        note_style
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
    story.append(Spacer(1, 6))

    from modules.optimizer import SECTION_ORDER, SECTION_LABELS
    section_order = optimization_result.get("section_order", SECTION_ORDER)
    section_labels = SECTION_LABELS

    # Render contact lines from header (no section title)
    if contact_lines:
        contact_text = "  |  ".join(contact_lines[:5])
        story.append(Paragraph(contact_text, ParagraphStyle(
            "Header", parent=styles["Normal"], fontName="Helvetica",
            fontSize=9.5, textColor=MUTED, alignment=TA_CENTER, spaceAfter=2)))
        story.append(Spacer(1, 8))

    for sec_key in section_order:
        if sec_key == "header":
            continue
        text = sections.get(sec_key, "")
        if not text or not text.strip():
            continue

        story.append(Paragraph(section_labels.get(sec_key, sec_key.title()), section_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=MUTED))
        story.append(Spacer(1, 4))

        lines = [l.strip() for l in text.split("\n") if l.strip()]
        for line in lines:
            clean_line = line.lstrip("•-*▸►→✓●◦").strip()
            if clean_line:
                is_bullet = line[0] in "•-*▸►→✓●◦" if line else False
                if is_bullet:
                    story.append(Paragraph(f"• {clean_line}", bullet_style))
                else:
                    story.append(Paragraph(clean_line, body_style))
        story.append(Spacer(1, 6))

    # Footer
    story.append(HRFlowable(width="100%", thickness=0.5, color=MUTED))
    story.append(Paragraph(
        f"Generated by AI Resume Analyzer Pro · {datetime.now().strftime('%B %d, %Y')}",
        ParagraphStyle("Footer", parent=styles["Normal"], fontName="Helvetica",
                       fontSize=8, textColor=MUTED, alignment=TA_CENTER)
    ))

    doc.build(story)
    return buffer.getvalue()


def generate_optimized_docx(optimization_result: dict, resume_name: str = "resume") -> bytes:
    """
    Generate a professionally formatted DOCX of the optimized resume.
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        return _fallback_text_export(optimization_result).encode("utf-8")

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

    ACCENT_COLOR = RGBColor(0x7c, 0x3a, 0xed)
    DARK_COLOR = RGBColor(0x1e, 0x1e, 0x2e)
    MUTED_COLOR = RGBColor(0x6b, 0x72, 0x80)

    sections = optimization_result.get("optimized_sections", {})
    est_score = optimization_result.get("estimated_new_ats_score", 0)
    improvement = optimization_result.get("improvement_percentage", 0)

    # Extract actual name and contact from header section
    sections_data = optimization_result.get("optimized_sections", {})
    header_text = sections_data.get("header", "")
    header_lines = [l.strip() for l in header_text.split("\n") if l.strip()]
    if header_lines:
        display_name = header_lines[0]
        contact_lines = header_lines[1:]
    else:
        display_name = resume_name.replace("_", " ").replace("-", " ").title()
        display_name = display_name.replace(".Pdf", "").replace(".Docx", "").replace(".Doc", "")
        contact_lines = []

    # Name heading
    name_para = doc.add_heading(display_name, level=1)
    name_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in name_para.runs:
        run.font.size = Pt(20)
        run.font.color.rgb = DARK_COLOR

    # Contact info on one line
    if contact_lines:
        contact_str = "  |  ".join(contact_lines[:5])
        sub = doc.add_paragraph(contact_str)
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in sub.runs:
            run.font.size = Pt(9)
            run.font.color.rgb = MUTED_COLOR

    # ATS score subtitle
    sub2 = doc.add_paragraph(
        f"ATS-Optimized Resume · Estimated Score: ~{est_score:.0f}% (↑{improvement:.0f}%)"
    )
    sub2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in sub2.runs:
        run.font.size = Pt(9)
        run.font.color.rgb = MUTED_COLOR
        run.font.italic = True

    doc.add_paragraph()

    from modules.optimizer import SECTION_ORDER, SECTION_LABELS
    section_order = optimization_result.get("section_order", SECTION_ORDER)
    section_labels = {k: v.upper() for k, v in SECTION_LABELS.items()}
    sections = sections_data

    for sec_key in section_order:
        if sec_key == "header":
            continue
        text = sections.get(sec_key, "")
        if not text or not text.strip():
            continue

        # Section heading
        h = doc.add_heading(section_labels.get(sec_key, sec_key.upper()), level=2)
        for run in h.runs:
            run.font.color.rgb = ACCENT_COLOR
            run.font.size = Pt(11)

        # Section content
        lines = [l.strip() for l in text.split("\n") if l.strip()]
        for line in lines:
            clean_line = line.lstrip("•-*▸►→✓●◦").strip()
            if not clean_line:
                continue
            is_bullet = len(line) > 0 and line[0] in "•-*▸►→✓●◦"
            if is_bullet:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(clean_line)
                run.font.size = Pt(10)
            else:
                p = doc.add_paragraph(clean_line)
                p.runs[0].font.size = Pt(10) if p.runs else None

    # Footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph(
        f"Generated by AI Resume Analyzer Pro · {datetime.now().strftime('%B %d, %Y')}"
    )
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_para.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = MUTED_COLOR
        run.font.italic = True

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _fallback_text_export(optimization_result: dict) -> str:
    """Plain-text fallback if PDF/DOCX libs unavailable."""
    sections = optimization_result.get("optimized_sections", {})
    lines = ["=" * 60, "AI-OPTIMIZED RESUME", "=" * 60, ""]
    for sec, text in sections.items():
        if text:
            lines += [f"\n{sec.upper()}", "-" * 40, text, ""]
    return "\n".join(lines)
